### ISSUE TITLE
Improvement: Optional resources cause errors in the deployment

### ISSUE THREAD

**Issue by Hurvester** [Azure/data-product-batch#121]
### Feature or Idea - What?

There are optional resources, such as CosmosDB or the unchosen ADF/Synapse, of which's module outcomes the new logging elements are dependent on. I believe that is the reason causing errors when deploying the Batch product straight out-of-the-box. 

Would ne a nice adding to make those logging parts work in a way it regards the optional resources as optional.

### Feature or Idea - Why?

To clean the code and not raising unnecessary errors.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-product-batch/blob/main/CODE_OF_CONDUCT.md)

**Comment by sudivate** [comment]
@Hurvester can you please share the error details and bicep version?

**Comment by Hurvester** [comment]
Hello!

Sure, this is the error I get:
{
    "status": "Failed",
    "error": {
        "code": "DeploymentNotFound",
        "message": "Deployment 'cosmos001' could not be found."
    }
}

And it is the latest commit's main.bicep:

 https://github.com/Azure/data-product-batch/commit/36b9f3a8d1115d0c3743432372e672bb0b5eba5b

**Comment by sudivate** [comment]
@Hurvester I believe the issue you are facing is related to this https://github.com/Azure/bicep/issues/3750  and  Bicep team is working on it.  Meanwhile one workaround is to update the references in  generated template as below 

Example:  If the `enableCosmos = false  `  in the params.json  the  references in the generated deployment template look like this 
```
"cosmosDBScope": {
    "value": "[reference(resourceId('Microsoft.Resources/deployments', 'cosmos001')).outputs.cosmosId.value]"
          }
```   

However, the correct reference in deployment template should be conditional as well and look like this.

```
"cosmosDBScope": {
   "value": "[if(parameters('enableCosmos'), reference(resourceId('Microsoft.Resources/deployments', 'cosmos001')).outputs.cosmosId.value, '')]"
          }
```

**Comment by marvinbuss** [comment]
@sudivate why don't you use the following Syntax in Bicep:

```bicep
cosmosId: enableCosmos ? cosmos001.outputs.cosmosId : ''
```
Have you tested this?

**Comment by sudivate** [comment]
I found that to be error prone in some cases but looks like [v0.4.1318](https://github.com/Azure/bicep/releases/tag/v0.4.1318) had   a fix for one such case.  Created a PR that updates all module parameters based on the options selected.
